version: '3.8'

services:
  db:
    image: postgres:14.2
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - finances

networks:
  finances:
