version: '3.8'

services:
  db:
    image: postgres:14.2
    ports:
      - 5438:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker-postgres
      POSTGRES_DB: finances
    networks:
      - finances

networks:
  finances:
